<?xml version="1.0" encoding="UTF-8"?>
<ActionCollection version="2" name="Scripts">
    <Actions category="Scripts">
        <text>Subwindow Recall</text>

        <Action name="loadSubwindows">
        <icon></icon>
        <text>Load Current Layout</text>
        <whatsThis>loads the size and positions from an existing .txt file of the same name as the document,
        stored in the same directory, it requires the same number of subwindows as the last time you have
        saved the subwindows layout</whatsThis>
        <toolTip></toolTip>
        <iconText></iconText>
        <activationFlags>10000</activationFlags>
        <activationConditions>0</activationConditions>
        <shortcut></shortcut>
        <isCheckable>false</isCheckable>
        <statusTip></statusTip>
        </Action>
        
        <Action name="subwindowMenu">
            <icon></icon>
            <text>Subwindow Menu</text>
            <whatsThis>Opens a GUI to manage layouts from Subwindow Recall</whatsThis>
            <toolTip></toolTip>
            <iconText></iconText>
            <activationFlags>10000</activationFlags>
            <activationConditions>0</activationConditions>
            <shortcut></shortcut>
            <isCheckable>false</isCheckable>
            <statusTip></statusTip>
        </Action>
    </Actions>
</ActionCollection>
